plugins:
  - node
extends: 'eslint:recommended'
env:
  node: true
  commonjs: true
  es6: true
rules:
  strict:
    - error
    - safe
  no-extend-native:
    - error
  no-bitwise:
    - error
  eqeqeq:
    - error
    - smart
  no-use-before-define:
    - error
    - functions: false
      classes: false
  node/no-unsupported-features:
    - error
    - version: 4
  no-caller:
    - error
  no-invalid-regexp:
    - error

  # styling
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  space-in-parens:
    - error
    - never
  computed-property-spacing: 
    - error
    - never
  array-bracket-spacing: 
    - error
    - never
  camelcase:
    - error
  curly:
    - error
  wrap-iife:
    - error
    - inside
  new-cap:
    - error
  no-trailing-spaces:
    - error
  comma-dangle:
    - error
    - never
